In [69]:
#importing necessory libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [70]:
#importing data

raw_data=np.genfromtxt("C:/Users/ABINESH/Downloads/loan-data.csv",delimiter=";",autostrip=True,skip_header=1)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [71]:
## Data cleaning Procedures
# Checking the shape of the dataset
raw_data.shape

(10000, 14)

In [72]:
## checking missing values
np.isnan(raw_data).sum()

88005

In [73]:
## temporary mean
temporary_mean=np.nanmean(raw_data,axis=0)
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [74]:
## capturing the indices of column containing string values

columns_string=np.argwhere(np.isnan(temporary_mean))
columns_string

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

In [75]:
## converting the above 2D output to 1D output for further use

columns_string=np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [76]:
## capturing numeric columns indices

columns_numeric=np.argwhere(np.isnan(temporary_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [77]:
## Capturing columns containig object/string values

loan_data_strings=np.genfromtxt("C:/Users/ABINESH/Downloads/loan-data.csv",delimiter=";",skip_header=1,
                               autostrip=True,usecols=columns_string,dtype=str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [78]:
## capturing columns containig numeric data
temporary_fill=np.nanmax(raw_data)+1
loan_data_numeric=np.genfromtxt("C:/Users/ABINESH/Downloads/loan-data.csv",delimiter=";",skip_header=1,
                               autostrip=True,usecols=columns_numeric,filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [79]:
## capturing headers

header_full=np.genfromtxt("C:/Users/ABINESH/Downloads/loan-data.csv",delimiter=";",autostrip=True,
                          skip_footer=raw_data.shape[0],dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [80]:
## Splitting headers for numeric data and string data

header_strings,header_numeric=header_full[columns_string],header_full[columns_numeric]
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [81]:
## Manipulating text data:issue date:
# 1.) renaming column name
header_strings[0]="issue_date"
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [82]:
##2.) Displaying 1st column
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [83]:
## 3.) unique values in the column "issue_date"

np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [84]:
## 4.) stripping the number 15 from the column "issue_date" since we know the data set is for the year 2015

loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [85]:
##5.) convertng month values to eqivalent month number

months=np.array([" ","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])
for i in range(13):
    loan_data_strings[:,0]=np.where(loan_data_strings[:,0]==months[i],i,loan_data_strings[:,0])
loan_data_strings[:,0]
np.unique(loan_data_strings[:,0])

array(['', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [86]:
## Manipulating text data "loan status" column
#unique values in "loan status and term" column
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [87]:
##Providing dummy variables to this column for better analysis,assigning "good" as 1 and "bad" as 0
status_bad=np.array(["","Charged off","Default","Late (31-120 days)"])
x=np.where(np.isin(loan_data_strings[:,1], status_bad),0,1)
x
loan_data_strings[:,1]=x
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [88]:
## Manipulation on "term" column
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [89]:
# strippin the string months from the column
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [91]:
## Renaming the column
header_strings[2]="term_months"

In [92]:
## assuming worst case scenario and replacing blank spaces with duration 60 months
loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=="","60",loan_data_strings[:,2])
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [93]:
## Manipulating text data "Grade" column
np.unique(loan_data_strings[:,3],return_counts=True)

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array([ 515, 1632, 2606, 2766, 1389,  816,  236,   40], dtype=int64))

In [95]:
## Replacing missing values with the 2nd highest occerence in the data
loan_data_strings[:,3]=np.where(loan_data_strings[:,3]=="",'B',loan_data_strings[:,3])
np.unique(loan_data_strings[:,3],return_counts=True)

(array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array([1632, 3121, 2766, 1389,  816,  236,   40], dtype=int64))

In [96]:
## Manipulating text data "subgrade" column
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

In [97]:
## Replacing missing values in "subgrade" column

for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=="")&(loan_data_strings[:,3]==i),i+"5",loan_data_strings[:,4])
loan_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [98]:
## unique values in the modified "subgrade" column
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [99]:
## Manipulating text data "verification status" column
loan_data_strings[:,5]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [100]:
## unique values in this columns
np.unique(loan_data_strings[:,5])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [101]:
## replacing the values in this column with dummy variables
loan_data_strings[:,5]=np.where((loan_data_strings[:,5]=="")|(loan_data_strings[:,5]=="Not Verified"),0,1)
loan_data_strings[:,5]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

In [102]:
##unique vales
np.unique(loan_data_strings[:,5])

array(['0', '1'], dtype='<U69')

In [105]:
loan_data_strings=np.delete(loan_data_strings,6,axis=1)
loan_data_strings

array([['5', '1', '36', 'C', 'C3', '1'],
       ['', '1', '36', 'A', 'A5', '1'],
       ['9', '1', '36', 'B', 'B5', '1'],
       ...,
       ['6', '1', '36', 'A', 'A5', '1'],
       ['4', '1', '36', 'D', 'D2', '1'],
       ['12', '1', '36', 'A', 'A4', '0']], dtype='<U69')

In [112]:
header_strings=np.delete(header_strings,6)
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status'],
      dtype='<U19')

In [107]:
## Manipulating Numeric data

loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [39]:
## looking for null vales in the data set
np.isnan(loan_data_numeric).sum()

0

In [104]:
## Numeric data column names

header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [40]:
temporary_fill=np.nanmax(raw_data)+1
temporary_fill

68616520.0

In [41]:
temporary_stats=np.array([np.nanmin(raw_data,axis=0),temporary_mean,
                         np.nanmax(raw_data,axis=0)])
temporary_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [42]:
## Filling "funded amount" column with worst case

loan_data_numeric[:,2]=np.where(loan_data_numeric[:,2]==temporary_fill,
                               temporary_stats[0,columns_numeric[2]],loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [43]:
## Filling missing values in other numeric columns with maximum value

for i in [1,3,4,5]:
    loan_data_numeric[:,i]=np.where(loan_data_numeric[:,i]==temporary_fill,
                                   temporary_stats[2,columns_numeric[i]],loan_data_numeric[:,i])
loan_data_numeric[:,4]

array([1184.86,  938.57,  494.86, ..., 1372.97,  354.3 ,  309.97])

In [109]:
loan_data_strings.shape

(10000, 6)

In [45]:
loan_data_numeric.shape

(10000, 6)

In [108]:
## Merging both string data and numeric data
clean_loan_data=np.hstack((loan_data_numeric,loan_data_strings))
clean_loan_data

array([['48010226.0', '35000.0', '35000.0', ..., 'C', 'C3', '1'],
       ['57693261.0', '30000.0', '30000.0', ..., 'A', 'A5', '1'],
       ['59432726.0', '15000.0', '15000.0', ..., 'B', 'B5', '1'],
       ...,
       ['50415990.0', '10000.0', '10000.0', ..., 'A', 'A5', '1'],
       ['46154151.0', '68616520.0', '10000.0', ..., 'D', 'D2', '1'],
       ['66055249.0', '10000.0', '10000.0', ..., 'A', 'A4', '0']], dtype='<U69')

In [114]:
## concatinating headers to our data
header_overall=np.concatenate((header_numeric,header_strings))
header_overall

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'issue_date',
       'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status'], dtype='<U19')

In [115]:
## Merging headers and their values
final_data=np.vstack((header_overall,clean_loan_data))
final_data

array([['id', 'loan_amnt', 'funded_amnt', ..., 'grade', 'sub_grade', 'verification_status'],
       ['48010226.0', '35000.0', '35000.0', ..., 'C', 'C3', '1'],
       ['57693261.0', '30000.0', '30000.0', ..., 'A', 'A5', '1'],
       ...,
       ['50415990.0', '10000.0', '10000.0', ..., 'A', 'A5', '1'],
       ['46154151.0', '68616520.0', '10000.0', ..., 'D', 'D2', '1'],
       ['66055249.0', '10000.0', '10000.0', ..., 'A', 'A4', '0']], dtype='<U69')

In [121]:
analysis_data=pd.DataFrame(final_data)
header_row=0
analysis_data.columns=analysis_data.iloc[header_row]
analysis_data=analysis_data.drop([0])
analysis_data.reset_index()
analysis_data
analysis_data.reset_index()
analysis_data

0              id   loan_amnt funded_amnt    int_rate installment total_pymnt  \
1      48010226.0     35000.0     35000.0       13.33     1184.86     9452.96   
2      57693261.0     30000.0     30000.0  68616520.0      938.57      4679.7   
3      59432726.0     15000.0     15000.0  68616520.0      494.86     1969.83   
4      53222800.0      9600.0      9600.0  68616520.0      300.35     1793.68   
5      57803010.0      8075.0      8075.0       19.19      296.78     1178.51   
...           ...         ...         ...         ...         ...         ...   
9996   42974433.0     18000.0     18000.0  68616520.0      565.56     5639.24   
9997   45424654.0     11300.0     11300.0  68616520.0      364.57     3274.86   
9998   50415990.0     10000.0     10000.0  68616520.0  68616520.0     2185.64   
9999   46154151.0  68616520.0     10000.0       16.55       354.3      3199.4   
10000  66055249.0     10000.0     10000.0  68616520.0      309.97       301.9   

0     issue_date loan_status term_months grade sub_grade verification_status  
1              5           1          36     C        C3                   1  
2                          1          36     A        A5                   1  
3              9           1          36     B        B5                   1  
4              7           1          36     A        A5                   0  
5              8           1          36     B        E3                   1  
...          ...         ...         ...   ...       ...                 ...  
9996           3           1          36     B        B1                   1  
9997           4           1          36     B        B3                   0  
9998           6           1          36     A        A5                   1  
9999           4           1          36     D        D2                   1  
10000         12           1          36     A        A4                   0  

[10000 rows x 12 columns]